services:
  webapp:
    build: ./webapp
    container_name: webapp
    restart: always
    environment:
      PHP_OPCACHE_ENABLE: 0
      PRODUCTION: 0
    ports:
      - 8080:80
      - 5173:5173
    volumes:
      - ./webapp:/var/www/webapp
      - geoglify-node-modules-data:/var/www/webapp/node_modules
      - geoglify-vendor-data:/var/www/webapp/vendor
      - geoglify-storage-data:/var/www/webapp/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://webapp/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - database

  database:
    build: ./database
    image: database
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - geoglify-database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

  mailpit:  
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - geoglify-mailpit-data:/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - geoglify-redis-data:/data
    ports:
      - 6379:6379
      
volumes:
  geoglify-vendor-data:
  geoglify-storage-data:
  geoglify-database-data:
  geoglify-node-modules-data:
  geoglify-mailpit-data:
  geoglify-redis-data:
