services:
  webapp:
    build: ./webapp
    container_name: webapp
    restart: always
    environment:
      PHP_OPCACHE_ENABLE: 0
      PRODUCTION: 0
    ports:
      - 8080:80
      - 5173:5173
    volumes:
      - ./webapp:/var/www/webapp
      - node_modules-data:/var/www/webapp/node_modules
      - vendor-data:/var/www/webapp/vendor
      - storage-data:/var/www/webapp/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://webapp/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - database

  database:
    build: ./database
    image: database
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

  mailpit:  
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mailpit_data:/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  ldap:
    image: osixia/openldap
    container_name: ldap
    environment:
        - LDAP_ORGANISATION=geoglify
        - LDAP_DOMAIN=geoglify.com
        - "LDAP_BASE_DN=dc=geoglify,dc=com"
        - LDAP_ADMIN_PASSWORD=geoglify
    ports:
        - 389:389
        - 636:636
      
volumes:
  vendor-data:
  storage-data:
  database-data:
  node_modules-data:
  mailpit_data:
  redis_data:
