services:
  webapp:
    build: ./webapp
    container_name: webapp
    environment:
      PHP_OPCACHE_ENABLE: 1
      PRODUCTION: 1
    ports:
      - 8080:80
      - 5173:5173
    volumes:
      - ./webapp:/opt/webapp
      - node_modules-data:/opt/webapp/node_modules
      - vendor-data:/opt/webapp/vendor
      - storage-data:/opt/webapp/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://webapp/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - database

  database:
    build: ./database
    image: database
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
      
volumes:
  vendor-data:
  storage-data:
  database-data:
  node_modules-data:
