services:
  webapp:
    build: ./webapp
    image: geoglify/webapp
    container_name: gwebapp
    restart: always
    environment:
      PHP_OPCACHE_ENABLE: 0
      PRODUCTION: 0
    ports:
      - 81:80
      - 8080:8080
      - 5173:5173
    volumes:
      - ./webapp:/var/www/webapp
      - geoglify-node-modules-data:/var/www/webapp/node_modules
      - geoglify-vendor-data:/var/www/webapp/vendor
    healthcheck:
      test: ["CMD", "curl", "-f", "http://webapp/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - database
      - redis

  database:
    build: ./database
    image: geoglify/database
    restart: always
    container_name: gdatabase
    ports:
      - "5432:5432"
    volumes:
      - geoglify-database-data:/var/lib/postgresql/data

  mailpit:  
    image: axllent/mailpit:latest
    container_name: gmailpit
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - geoglify-mailpit-data:/data

  redis:
    image: redis:latest
    container_name: gredis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - geoglify-redis-data:/data
    ports:
      - 6379:6379

  redis-insight:
    image: redis/redisinsight:latest
    container_name: gredisinsight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - geoglify-redis-insight-data:/data

  ldap:
    image: osixia/openldap:1.5.0
    container_name: gldap
    environment:
        - LDAP_ORGANISATION=exampleorg
        - LDAP_DOMAIN=example.in
        - "LDAP_BASE_DN=dc=example,dc=in"
        - LDAP_ADMIN_PASSWORD=password
    ports:
        - 389:389
        - 636:636

  ais-stream:
    build: ./ais-stream
    container_name: gaisstream
    working_dir: /opt/ais-stream
    environment:
      - NODE_ENV=production
      - AISSTREAM_API_KEY=7fb1e16f93a4d520d83a95e325c55e69b3b4fc0b
      - AIS_SERVER_HOST=aisstream.io
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: "node main.js"
    depends_on:
      - redis
    
volumes:
  geoglify-vendor-data:
  geoglify-storage-data:
  geoglify-database-data:
  geoglify-node-modules-data:
  geoglify-mailpit-data:
  geoglify-redis-data:
  geoglify-redis-insight-data: